name: Issue about a bug
description: Make a suggestion to resolve a bug.
title: "[Bug] "
projects: ["Arknights mcp"]
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What is the bug?
      description: Please explain in detail.
    validations:
      required: true
    