name: Issue about a new feature
description: Make a suggestion to improve the feature.
title: "[Feature] "
projects: ["gjeodnd12165/4"]
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What is the feature?
      description: Please explain in detail.
    validations:
      required: true
    